export VLLM_ATTENTION_BACKEND=XFORMERS

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=$HOME/data/npuzzle/train.parquet \
 data.val_files=$HOME/data/npuzzle/test.parquet \
 data.train_batch_size=128 \
 data.max_prompt_length=2048 \
 data.max_response_length=1500 \
 actor_rollout_ref.model.path=../model/Qwen/Qwen2.5-7B-Instruct-1M \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=32 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=5e-6 \
 critic.model.path=../model/Qwen/Qwen2.5-7B-Instruct-1M \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.0 \
 trainer.logger=['console','wandb'] \
 trainer.default_hdfs_dir=null \
 trainer.n_gpus_per_node=8 \
 trainer.nnodes=1 \
 trainer.save_freq=500 \
 trainer.test_freq=10 \
 trainer.total_training_steps=2000 \
 trainer.project_name='ppo_r1_point24_v3' \
 trainer.experiment_name='ppo_r1_point24_track_v3' \
 trainer.total_epochs=2000 2>&1 | tee verl_demo.log